// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALKQCXjgkFrOsPmgowgE8GfOI_NkYFsIY',
    appId: '1:657838106737:web:46ac8b83a3c069967593d0',
    messagingSenderId: '657838106737',
    projectId: 'timewisefinal',
    authDomain: 'timewisefinal.firebaseapp.com',
    storageBucket: 'timewisefinal.appspot.com',
    measurementId: 'G-LYMT8LL4XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYduAJlkxak0s3lDWbIIIQaaGphv8QALo',
    appId: '1:657838106737:android:7644279994e61bad7593d0',
    messagingSenderId: '657838106737',
    projectId: 'timewisefinal',
    storageBucket: 'timewisefinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqXJAXjD579WlMS2uXkfrd3rf6SzglrI',
    appId: '1:657838106737:ios:7232f23d6cd1ea2c7593d0',
    messagingSenderId: '657838106737',
    projectId: 'timewisefinal',
    storageBucket: 'timewisefinal.appspot.com',
    iosClientId: '657838106737-cfdnq0mj6sg6st44h8koami85nv4di4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.timewise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWqXJAXjD579WlMS2uXkfrd3rf6SzglrI',
    appId: '1:657838106737:ios:7232f23d6cd1ea2c7593d0',
    messagingSenderId: '657838106737',
    projectId: 'timewisefinal',
    storageBucket: 'timewisefinal.appspot.com',
    iosClientId: '657838106737-cfdnq0mj6sg6st44h8koami85nv4di4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.timewise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALKQCXjgkFrOsPmgowgE8GfOI_NkYFsIY',
    appId: '1:657838106737:web:b039f48c1ba32b337593d0',
    messagingSenderId: '657838106737',
    projectId: 'timewisefinal',
    authDomain: 'timewisefinal.firebaseapp.com',
    storageBucket: 'timewisefinal.appspot.com',
    measurementId: 'G-JM7SQLFGQH',
  );

}